In [11]:
import numpy as np

In [12]:
a = np.array([1,2,3,4])
a.dtype

dtype('int32')

In [13]:
a.ndim

1

In [14]:
a.size

4

In [15]:
a.shape

(4,)

In [16]:
l, = a.shape
l

4

In [17]:
a.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [20]:
(a>2).flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [21]:
a[2:].flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [24]:
(a[a>2]).flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [25]:
a[a>2] is a

False

In [26]:
id(a)

2377246501024

In [27]:
id(a[a>2])

2377251027264

In [29]:
(a>2).nonzero()

(array([2, 3], dtype=int64),)

In [30]:
a[(a>2).nonzero()]

array([3, 4])

In [33]:
a[[2,3]]=0
a

array([1, 2, 0, 0])

In [34]:
(a[[2,3]]).flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [41]:
a = np.arange(0,25).reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [42]:
a[1,2] = 5
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  5,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [43]:
a[:,1] = 0
a

array([[ 0,  0,  2,  3,  4],
       [ 5,  0,  5,  8,  9],
       [10,  0, 12, 13, 14],
       [15,  0, 17, 18, 19],
       [20,  0, 22, 23, 24]])

In [45]:
a[[2,4]] = 1
a

array([[ 0,  0,  2,  3,  4],
       [ 5,  0,  5,  8,  9],
       [ 1,  1,  1,  1,  1],
       [15,  0, 17, 18, 19],
       [ 1,  1,  1,  1,  1]])

In [47]:
a[a<2] = 0
a

array([[ 0,  0,  2,  3,  4],
       [ 5,  0,  5,  8,  9],
       [ 0,  0,  0,  0,  0],
       [15,  0, 17, 18, 19],
       [ 0,  0,  0,  0,  0]])

In [48]:
a = np.array([4,7,8])

In [49]:
a<2

array([False, False, False])

In [51]:
a[a<5]

array([4])

In [53]:
a[(a<5).nonzero()]

array([4])

In [54]:
(a<5).nonzero()

(array([0], dtype=int64),)

In [55]:
a<5

array([ True, False, False])

In [57]:
b, = (a<5).nonzero()

In [58]:
b

array([0], dtype=int64)

In [59]:
a[b]

array([4])

In [60]:
a = np.arange(25).reshape(5,5)

In [61]:
a[np.array([[i for i in range(1,5)],[j for j in range(0,4)]])]

array([[[ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [67]:
b = np.array([[i for i in range(0,4)],[j for j in range(1,5)]])

In [68]:
a[b]

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]]])

In [64]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [69]:
b

array([[0, 1, 2, 3],
       [1, 2, 3, 4]])

In [70]:
a[[i for i in range(0,4)],[j for j in range(1,5)]]

array([ 1,  7, 13, 19])

In [71]:
a[a%3==0]

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24])

In [72]:
a%3==0

array([[ True, False, False,  True, False],
       [False,  True, False, False,  True],
       [False, False,  True, False, False],
       [ True, False, False,  True, False],
       [False,  True, False, False,  True]])

In [73]:
a[a>3==True]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [74]:
a = np.arange(40).reshape(4,5,2)

In [75]:
b = np.arange(8).reshape(4,1,2)

In [76]:
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]]])

In [77]:
b

array([[[0, 1]],

       [[2, 3]],

       [[4, 5]],

       [[6, 7]]])

In [78]:
a+b

array([[[ 0,  2],
        [ 2,  4],
        [ 4,  6],
        [ 6,  8],
        [ 8, 10]],

       [[12, 14],
        [14, 16],
        [16, 18],
        [18, 20],
        [20, 22]],

       [[24, 26],
        [26, 28],
        [28, 30],
        [30, 32],
        [32, 34]],

       [[36, 38],
        [38, 40],
        [40, 42],
        [42, 44],
        [44, 46]]])

In [79]:
np.sum([1,np.nan,10])

nan

In [80]:
np.nansum([1,np.nan,10])

11.0

In [81]:
np.sum(a,axis=-1)

array([[ 1,  5,  9, 13, 17],
       [21, 25, 29, 33, 37],
       [41, 45, 49, 53, 57],
       [61, 65, 69, 73, 77]])

In [82]:
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]]])

In [83]:
np.sum(a,axis=-2)

array([[ 20,  25],
       [ 70,  75],
       [120, 125],
       [170, 175]])

In [85]:
[1,2,3]*2

[1, 2, 3, 1, 2, 3]

In [86]:
'abc'*2

'abcabc'

In [87]:
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]]])

In [89]:
b = a[1,:,:]

In [90]:
b.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [91]:
b

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [92]:
b[0,0]=100

In [93]:
b

array([[100,  11],
       [ 12,  13],
       [ 14,  15],
       [ 16,  17],
       [ 18,  19]])

In [94]:
a

array([[[  0,   1],
        [  2,   3],
        [  4,   5],
        [  6,   7],
        [  8,   9]],

       [[100,  11],
        [ 12,  13],
        [ 14,  15],
        [ 16,  17],
        [ 18,  19]],

       [[ 20,  21],
        [ 22,  23],
        [ 24,  25],
        [ 26,  27],
        [ 28,  29]],

       [[ 30,  31],
        [ 32,  33],
        [ 34,  35],
        [ 36,  37],
        [ 38,  39]]])